"""Vector and protocol type inference for spatial math (Vector3, Quaternion) and network struct declarations."""

from __future__ import annotations

import re
from typing import Any

from re_agent.utils.paths import safe_identifier


def _component_name(value: object) -> tuple[str, str] | None:
    name = str(value).strip().casefold()
    name = re.sub(r"^m_", "", name)
    match = re.fullmatch(r"(.*?)(?:_)?([xyzw])", name)
    if not match:
        return None
    return match.group(1).rstrip("_"), match.group(2)


def infer_vector_types(fields: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Group only name- and offset-proven vector/quaternion components."""
    if not fields:
        return []

    sorted_fields = sorted(fields, key=lambda f: f.get("offset", 0))
    inferred: list[dict[str, Any]] = []
    idx = 0
    n = len(sorted_fields)

    while idx < n:
        field = sorted_fields[idx]
        f_type = field.get("type", "").lower()
        f_offset = field.get("offset", 0)

        # Check if 3 consecutive float fields are present (Vector3 candidate)
        if (
            f_type == "float"
            and idx + 2 < n
            and sorted_fields[idx + 1].get("type", "").lower() == "float"
            and sorted_fields[idx + 2].get("type", "").lower() == "float"
            and sorted_fields[idx + 1].get("offset", 0) == f_offset + 4
            and sorted_fields[idx + 2].get("offset", 0) == f_offset + 8
        ):
            components = [_component_name(sorted_fields[idx + component].get("name", "")) for component in range(3)]
            if (
                any(component is None for component in components)
                or [component[1] for component in components if component] != ["x", "y", "z"]
                or len({component[0] for component in components if component}) != 1
            ):
                inferred.append(field)
                idx += 1
                continue
            # Check if a 4th float is part of a 4D Vector / Quaternion (e.g., named w, quat, rot)
            f4 = sorted_fields[idx + 3] if idx + 3 < n else None
            f4_component = _component_name(f4.get("name", "")) if f4 else None
            if (
                f4
                and f4.get("type", "").lower() == "float"
                and f4.get("offset", 0) == f_offset + 12
                and f4_component is not None
                and f4_component[1] == "w"
                and f4_component[0] == components[0][0]  # type: ignore[index]
            ):
                inferred.append(
                    {
                        "name": field.get("name", "rotation"),
                        "type": "Quaternion",
                        "offset": f_offset,
                        "size": 16,
                    }
                )
                idx += 4
                continue

            inferred.append(
                {
                    "name": field.get("name", "position"),
                    "type": "Vector3",
                    "offset": f_offset,
                    "size": 12,
                }
            )
            idx += 3
            continue

        inferred.append(field)
        idx += 1

    return inferred


def generate_protocol_struct(packet_name: str, payload_fields: list[dict[str, Any]]) -> str:
    """Generate a packed layout with explicit gaps and offset assertions."""
    packet_id = safe_identifier(packet_name)
    inferred_fields = infer_vector_types(payload_fields)
    uses_vector3 = any(field.get("type") == "Vector3" for field in inferred_fields)
    uses_quaternion = any(field.get("type") == "Quaternion" for field in inferred_fields)
    lines: list[str] = [
        "// Auto-generated by re-agent protocol type inferencer",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
    ]
    if uses_vector3:
        lines.extend(
            [
                "struct ReAgentVector3 { float x; float y; float z; };",
                "static_assert(sizeof(ReAgentVector3) == 12);",
                "",
            ]
        )
    if uses_quaternion:
        lines.extend(
            [
                "struct ReAgentQuaternion { float x; float y; float z; float w; };",
                "static_assert(sizeof(ReAgentQuaternion) == 16);",
                "",
            ]
        )
    lines.extend(["#pragma pack(push, 1)", f"struct {packet_id} {{"])

    type_layouts: dict[str, tuple[str, int]] = {
        "bool": ("bool", 1),
        "char": ("char", 1),
        "int8_t": ("std::int8_t", 1),
        "uint8_t": ("std::uint8_t", 1),
        "int16_t": ("std::int16_t", 2),
        "uint16_t": ("std::uint16_t", 2),
        "int32_t": ("std::int32_t", 4),
        "uint32_t": ("std::uint32_t", 4),
        "int64_t": ("std::int64_t", 8),
        "uint64_t": ("std::uint64_t", 8),
        "float": ("float", 4),
        "double": ("double", 8),
        "Vector3": ("ReAgentVector3", 12),
        "Quaternion": ("ReAgentQuaternion", 16),
    }
    assertions: list[str] = []
    cursor = 0
    pad_index = 0
    for index, field in enumerate(sorted(inferred_fields, key=lambda item: item.get("offset", 0))):
        field_name = safe_identifier(str(field.get("name") or f"field_{index}"))
        raw_type = str(field.get("type", "uint8_t"))
        layout = type_layouts.get(raw_type)
        field_offset = field.get("offset")
        if (
            layout is None
            or not isinstance(field_offset, int)
            or isinstance(field_offset, bool)
            or field_offset < cursor
        ):
            lines.append(
                f"    // Skipped unresolved/overlapping field {field_name} "
                f"(type={raw_type!r}, offset={field_offset!r})."
            )
            continue
        if field_offset > cursor:
            gap = field_offset - cursor
            lines.append(f"    std::uint8_t _pad_{pad_index}[0x{gap:X}];")
            pad_index += 1
            cursor = field_offset
        cpp_type, size = layout
        lines.append(f"    {cpp_type} {field_name}; // verified offset: 0x{field_offset:X}")
        assertions.append(f"static_assert(offsetof({packet_id}, {field_name}) == 0x{field_offset:X});")
        cursor += size

    lines.extend(
        [
            "};",
            "#pragma pack(pop)",
            *assertions,
        ]
    )
    return "\n".join(lines)
