"""Conservative C++ offset-inventory generation from binary evidence."""
from __future__ import annotations

from typing import Any

from re_agent.utils.paths import safe_identifier


def _comment(value: object) -> str:
    return str(value).replace("\r", " ").replace("\n", " ").replace("*/", "* /")[:300]


def generate_vtable_header(
    class_name: str,
    vtable_entries: list[dict[str, Any]],
    field_offsets: list[dict[str, Any]] | None = None,
) -> str:
    """Generate offset constants without inventing a compilable object layout.

    An address or field offset does not prove padding, field size, inheritance,
    pointer width, or a callable method ABI. Emitting constants keeps the
    evidence useful while forcing downstream code to make those decisions
    explicitly.
    """
    class_id = safe_identifier(class_name)
    lines: list[str] = [
        "// Auto-generated by re-agent from evidence-backed offsets.",
        "// This is an offset inventory, not a verified C++ object layout or ABI.",
        "#pragma once",
        "#include <cstdint>",
        "",
        f"struct {class_id}VTableOffsets {{",
    ]

    emitted_vtable = 0
    for index, entry in enumerate(vtable_entries):
        offset = entry.get("offset")
        if not isinstance(offset, int) or offset < 0:
            continue
        name = safe_identifier(str(entry.get("name") or f"slot_{index}"))
        lines.append(
            f"    static constexpr std::uintptr_t k_{name} = 0x{offset:X}; "
            f"// signature unverified: {_comment(entry.get('return_type', 'unknown'))}"
        )
        emitted_vtable += 1
    if not emitted_vtable:
        lines.append("    // No verified vtable-slot offsets were supplied.")
    lines.extend(["};", "", f"struct {class_id}FieldOffsets {{"])

    emitted_fields = 0
    for index, field in enumerate(sorted(field_offsets or [], key=lambda item: item.get("offset", 0))):
        offset = field.get("offset")
        if not isinstance(offset, int) or offset < 0:
            continue
        name = safe_identifier(str(field.get("name") or f"field_{index}"))
        lines.append(
            f"    static constexpr std::uintptr_t k_{name} = 0x{offset:X}; "
            f"// observed type: {_comment(field.get('type', 'unknown'))}"
        )
        emitted_fields += 1
    if not emitted_fields:
        lines.append("    // No verified field offsets were supplied.")
    lines.extend(["};", ""])
    return "\n".join(lines)
